; Generated by AutoGUI 2.1.7a
#NoEnv
#SingleInstance Force
SetWorkingDir %A_ScriptDir%

Gui Add, GroupBox, x18 y55 w450 h146 vButton1, Statistik
Gui Add, Text, x40 y83 w47 h13 vStatic1, &Auswahl:
Gui Add, ComboBox, x93 y80 w131 vComboBox1, 03221|32026|32880|80032|ABT|ABT BARMER|ABT TKK|alle_Pat|Anam,Bef|AOK|AOK 2|AOK 95051|AOKo93511|BARMER|dia F*|diagnosen|Fastjekt|GB|GVU|GVU fehlen|GVU2|Hausbesuch|J1|kein03362|keine01740|keine03220|keine03221|keine03360|kinder|Laboraussc|Lkn|nancy 0336|neuPat|notfall|Physio|Private|Privatp|Rheuma|Sarkoidose|Zeitraum|-03230
Gui Add, Text, x40 y112 w162 h13 vStatic2, &Beschreibung (max. 64 Zeichen):
Gui Add, Edit, x40 y133 w387 h57 +Multi vEdit2
Gui Add, GroupBox, x18 y268 w450 h67 vButton2, Datum
Gui Add, Radio, x40 y288 w47 h16 vButton3, &Heute
Gui Add, Radio, x127 y288 w60 h16 +Checked vButton4, &Zeitraum
Gui Add, Text, x204 y289 w24 h13 vStatic3, &von:
Gui Add, Edit, x232 y286 w62 h20 vEdit3, 01.07.2018
Gui Add, Text, x309 y289 w20 h13 vStatic4, b&is:
Gui Add, Edit, x331 y286 w62 h20 vEdit4, 30.09.2018
Gui Add, Radio, x40 y310 w59 h16 vButton5, &Quartal
Gui Add, DropDownList, x115 y309 w65 +Disabled vComboBox2, Aktuell|2/18|1/18|4/17|3/17|2/17|1/17|4/16|3/16|2/16|1/16|4/15|3/15|2/15|1/15|4/14|3/14|2/14|1/14|4/13|3/13|2/13|1/13|4/12|3/12|2/12|1/12|4/11|3/11|2/11
Gui Add, Button, x100 y356 w75 h23 +Disabled vButton6, &Neu
Gui Add, Button, x196 y356 w75 h23 +Disabled vButton7, &Ändern
Gui Add, Button, x292 y356 w75 h23 +Disabled vButton8, &Löschen
Gui Add, Button, x148 y401 w75 h23 vButton9, &Übernehmen
Gui Add, Button, x247 y401 w75 h23 +Default vButton10, &Rückgängig
Gui Add, GroupBox, x256 y67 w195 h57 vButton11, Patienten
Gui Add, CheckBox, x264 y86 w99 h13 vButton12, Selektierte Liste
Gui Add, Text, x265 y104 w173 h15 vStatic5, Aktuell: Keine Liste im Hintergrund!
Gui Add, GroupBox, x18 y210 w450 h47 vButton13, Symbol
Gui Add, CheckBox, x28 y231 w152 h16 vButton14, Anzeige in Funktionleiste
Gui Add, Text, x217 y232 w116 h13 vStatic6, Kürzel für Funktionleiste
Gui Add, Edit, x346 y229 w104 h20 vEdit5, GB
Gui Add, Button, x200 y457 w75 h23 +Disabled vButton15, OK
Gui Add, Button, x281 y457 w75 h23 vButton16, Abbrechen
Gui Add, Button, x362 y457 w75 h23 +Disabled vButton17, Zurücksetzen
Gui Add, Button, x443 y457 w75 h23 vButton18, Hilfe
Gui Add, Tab3, x6 y7 w512 h444 vSysTabControl321,        >>>>    Menü    <<<<             |      Karteikarte      |      Medikamente      |      Schein      |       Patient      |Patient(2)|      Ausgabe

Gui Show, w524 h487, Freie Statistik  GB (Clone)
Return

GuiEscape:
GuiClose:
    ExitApp

; Do not edit above this line