; Generated by AutoGUI 2.1.7a
#NoEnv
#SingleInstance Force
SetBatchLines, -1
SetWinDelay, -1
SetControlDelay, -1
SetWorkingDir %A_ScriptDir%
SetTitleMatchMode, 2
CoordMode, Pixel, Client
#include %A_ScriptDir%\..\Praxomat_Functions.ahk
#include %A_ScriptDir%\..\Gdip_All.ahk

WinMinimize, ahk_class SciTEWindow

WinActivate, ALBIS ahk_class OptoAppClass
AlbisWinID:= WinExist("ALBIS ahk_class OptoAppClass")

PostMessage, 0x111, 33311,,, ahk_id %AlbisWinID%

WinWait, Heilmittelverordnung ahk_class #32770

OPhy:= Object()
hOrigPhys:= WinExist("Heilmittelverordnung ahk_class #32770")
OPhy:= GetWindowInfo(hOrigPhys)

pToken := Gdip_Startup()
pBitmap := Gdip_BitmapFromhwnd(hOrigPhys)
x:=9, y:=58, w:=303, h:=152
pBitmap_area:=Gdip_CloneBitmapArea(pBitmap, x, y, w, h)
hBitmap_area:= Gdip_CreateHBITMAPFromBitmap(pBitmap_area)
Gdip_DisposeImage(pBitmap)
Gdip_DisposeImage(pBitmap_area)

Buttons:= "CB1_Group(3,4),CB2_Group(5,6),7,8,9,11,CB3_Group(13,14,15),18,CB4_Group(19,20),CB4_Group(21,22),24,27,CB5_Group(35,36),  "
Edits:= "4,Ed1_Group(6,7,8),Ed2_Group(10,11,12),Ed3_Group(22,23),26,27,Ed4_Group(30,29),Ed5_Group(32,29),31,35,36"

;Gui Add, UpDown, x614 y4 w17 h17 -16 vmsctls_updown321
;Standard Muster13.1
Gui, Phy:  +AlwaysOnTop
Gui, Phy: Color, cb7e4f9
Gui, Margin, 0, 0
Gui, Phy:  Add, GroupBox		, x6 y20 w642 h942 cFFFFFF					vButton2
Gui, Phy:  Add, Picture			, x8 y29 w303 h152 								vStammdaten, HBitmap: %hBitmap_area%
Gui, Phy:  Add, Text				, x411 y63 w144 h20 		+Center 		vStatic1			, Heilmittelverordnung 13
Gui, Phy:  Add, Text				, x356 y91 w132 h49 							vStatic2			, Maßnahmen der Physikalischen Therapie/ Podologischen Therapie
Gui, Phy:  Add, Radio			, x356 y140 w164 h16 		+Checked 	vButton3		, Physikalische Therapie
Gui, Phy:  Add, Radio			, x356 y161 w134 h16 							vButton4		, Podologische Therapie
Gui, Phy:  Add, CheckBox		, x8 y193 w57 h26 								vButton5		, Geb&ühr- pfl.
Gui, Phy:  Add, CheckBox		, x71 y193 w57 h26 								vButton6		, Gebühr &frei
Gui, Phy:  Add, CheckBox		, x131 y187 w56 h41 							vButton7		, &Unfall/ Unfall folgen
Gui, Phy:  Add, CheckBox		, x203 y193 w44 h26 							vButton8		, BVG
Gui, Phy:  Add, CheckBox		, x248 y190 w80 h31							vButton9		, Arbeitsunfall
Gui, Phy:  Add, GroupBox		, x6 y226 w632 h159 cFFFFFF				vButton12
Gui, Phy:  Add, Text				, x14 y237 w287 h16 							vStatic3			, Verordnung nach Maßgabe des Kataloges (Regelfall)
Gui, Phy:  Add, Radio			, x14 y258 w74 h28 			+Checked 	vButton13		, Erst- &verordnung
Gui, Phy:  Add, Radio			, x105 y257 w74 h31 							vButton14		, Folge- verordnung
Gui, Phy:  Add, Radio			, x203 y258 w129 h29 							vButton15		, Verordnung außerhalb des Regelfalles
Gui, Phy:  Add, CheckBox		, x459 y258 w66 h31 							vButton18		, &Gruppen- therapie
Gui, Phy:  Add, Text				, x527 y237 w98 h28 							vStatic5			, Behandlungsbeginn sp&ätest. am:
Gui, Phy:  Add, Edit				, x531 y268 w77 h21 							vEdit4
Gui, Phy:  Add, Text				, x14 y338 w62 h13 								vStatic6			, Hausbesuch
Gui, Phy:  Add, Radio			, x15 y358 w35 h16 								vButton19		, &Ja
Gui, Phy:  Add, Radio			, x57 y358 w47 h16 			+Checked 	vButton20		, &Nein
Gui, Phy:  Add, Text				, x443 y328 w153 h13 							vStatic7			, Therapiebericht
Gui, Phy:  Add, Radio			, x443 y346 w54 h26 							vButton21		, Ja
Gui, Phy:  Add, Radio			, x507 y346 w63 h26 		+Checked 	vButton22		, Nein
Gui, Phy:  Add, Text				, x11 y400 w66 h26 			+Center 		vStatic8			, Verordnungs- &menge
Gui, Phy:  Add, Text				, x146 y413 w246 h16 		+Center 		vStatic11		, &Heilmittel nach Maßgabe des Kataloges
Gui, Phy:  Add, Text				, x503 y398 w42 h26 		+Center 		vStatic15		, Anzahl &pro Wo.
Gui, Phy:  Add, Text				, x555 y400 w39 h29 		+Center 		vStatic16		, Anmerk.
Gui, Phy:  Add, Text				, x594 y400 w51 h28 							vStatic17		, LHM`ngenehmigt
Gui, Phy:  Add, Edit				, x14 y431 w36 h23 								vEdit6
Gui, Phy:  Add, Edit				, x54 y431 w446 h23 							vEdit7
Gui, Phy:  Add, Edit				, x504 y431 w50 h23 							vEdit8
Gui, Phy:  Add, Button			, x561 y432 w24 h20 							vButton23
Gui, Phy:  Add, CheckBox		, x600 y434 w15 h16 							vButton24
Gui, Phy:  Add, Edit				, x14 y455 w36 h23 								vEdit10
Gui, Phy:  Add, Edit				, x54 y455 w446 h23 							vEdit11
Gui, Phy:  Add, Edit				, x504 y455 w50 h23 							vEdit12
Gui, Phy:  Add, Button			, x561 y457 w24 h20 							vButton26
Gui, Phy:  Add, CheckBox		, x600 y458 w15 h16 							vButton27
Gui, Phy:  Add, Text				, x12 y483 w65 h28 								vStatic18		, Ausnahme-`ngenehmigung
Gui, Phy:  Add, CheckBox		, x35 y516 w12 h13 								vButton35
Gui, Phy:  Add, Text				, x53 y509 w26 h13 								vStatic19		, ____
Gui, Phy:  Add, CheckBox		, x83 y516 w12 h13 								vButton36
Gui, Phy:  Add, Text				, x99 y516 w134 h13 							vStatic20		, Langfristiger Heilmittelbedarf
Gui, Phy:  Add, Text				, x306 y496 w72 h13 							vStatic21		, Genehmigt bis:
Gui, Phy:  Add, Edit				, x306 y513 w80 h20 							vEdit22
Gui, Phy:  Add, Text				, x411 y496 w144 h13 							vStatic22		, Bemerkung zur Genehmigung:
Gui, Phy:  Add, Edit				, x411 y513 w225 h20 							vEdit23
Gui, Phy:  Add, CheckBox		, x83 y537 w12 h13 								vButton38
Gui, Phy:  Add, Text				, x99 y537 w149 h13 							vStatic24		, Besonderer Verordnungsbedarf
Gui, Phy:  Add, Text				, x458 y581 w80 h13 							vStatic27		, Akutereignis am:
Gui, Phy:  Add, Edit				, x557 y579 w80 h20 							vEdit26
Gui, Phy:  Add, Text				, x94 y607 w303 h15 							vStatic28		, Diagnose mit Leits&ymptomatik, ggf. wesentliche Befunde
Gui, Phy:  Add, Edit				, x14 y633 w57 h20 							 	vEdit27
Gui, Phy:  Add, Text				, x14 y607 w53 h26 								vStatic29		, Indikations- schlüssel
Gui, Phy:  Add, Edit				, x86 y623 w551 h37 		+Multi 			vEdit29
Gui, Phy:  Add, Edit				, x14 y669 w57 h20 								vEdit30
Gui, Phy:  Add, Text				, x14 y656 w69 h13 								vStatic30		, ICD-10 - Code
Gui, Phy:  Add, Edit				, x86 y662 w551 h73 		+Multi 			vEdit31
Gui, Phy:  Add, Text				, x14 y696 w69 h13 								vStatic31		, ICD-10 - Code
Gui, Phy:  Add, Edit				, x14 y711 w57 h20 								vEdit32
Gui, Phy:  Add, Text				, x14 y775 w303 h15 							vStatic33		, Ggf. Spe&zifizierung der Therapieziele
Gui, Phy:  Add, Edit				, x14 y791 w453 h46 		+Multi 			vEdit35
Gui, Phy:  Add, Text				, x14 y850 w434 h15 							vStatic34		, Medizinische Begründung bei Verordnungen au&ßerhalb des Regelfalles (ggf. Beiblatt)
Gui, Phy:  Add, Edit				, x14 y867 w453 h86 		+Multi 			vEdit36
Gui, Phy:  Add, Progress     	, x00 y963 w954 h30 Background202842
;Gui, Phy:  Add, Progress     	, x00 y963 w954 h2 BackgroundFFFFFF


;Muster13.1 Automatisierungsfeatures
Gui, Phy:  Add, Button          , x10 y2        vFeature1 gPhyButtons   							, neues Formular
Gui, Phy:  Add, Button          , x100 y2      vFeature2 gPhyButtons   							, Formular ändern
Gui, Phy:  Add, Button          , x200 y2      vFeature3 gPhyButtons   							, Formular löschen
Gui, Phy:  Add, Button          , x300 y2      vFeature4 gPhyButtons   							, Daten vom Original holen
Gui, Phy:  Add, Button          , x500 y2      vFeature5 gPhyButtons   							, Daten nach Albis übertragen
Gui, Phy:  Add, ListView        , x650 y26 w290 h935 vLV1 gPhyButtons   , vorhandene Standardformulare
Gui, Phy: Font, S24, Futura Md Bk
Gui, Phy: Add, Text				, x22 y960 w600 cFFFFFF	BackgroundTrans										, Addendum für Albis on Windows
Gui, Phy: Font, S20, Futura Bk Bt italic
Gui, Phy: Add, Text				, x580 y961 w300 cFFFFFF	BackgroundTrans										, "Die wahre Ausfüllhilfe!"
OPhy:= GetWindowInfo(hOrigPhys)
PhyH:= (OPhy.WindowH - 29) < 1020 ? 1020 : (OPhy.WindowH - 29)
Gui, Phy:  Show, % "x" (OPhy.WindowX) " y" OPhy.WindowY " w" 946 " h" 993 , Muster 13.1 (01.2017), Heilmittelverordnung für %Pat% ausstellen (Clone)
Return

PhyButtons:

return


PhyGuiEscape:
PhyGuiClose:

Gdip_Shutdown(pToken)
	ExitApp

; Do not edit above this line